GET http://localhost:3000/urls/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzgxMzMyOTY0LCJleHAiOjE3ODEzMzY1NjQsImF1ZCI6ImNoZXJ1dGgtdXNlcnMiLCJpc3MiOiJjaGVydXRoLWFwaSJ9.qzDjA-qJAKWpVRCLjsqINsunfwgsIpWqcX_QkKYOWjc
