GET http://localhost:3000/api/urls/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzgxNTI4MTE3LCJleHAiOjE3ODE1MzE3MTcsImF1ZCI6ImNoZXJ1dGgtdXNlcnMiLCJpc3MiOiJjaGVydXRoLWFwaSJ9.PAm4NsaJKFlrCL3zcNjn-_e9iMfjy9HrT7n6RBVaD-c
