POST http://localhost:3000/api/urls
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZW1hZWlsQGdtYWlsLmNvbSIsImlhdCI6MTc4MTMzNDM0MCwiZXhwIjoxNzgxMzM3OTQwLCJhdWQiOiJjaGVydXRoLXVzZXJzIiwiaXNzIjoiY2hlcnV0aC1hcGkifQ.9g8Iany8KNDF4D7ZG6uoMKuyI7Eiaf5pSCut24j5zZw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzgxNTI4MTE3LCJleHAiOjE3ODE1MzE3MTcsImF1ZCI6ImNoZXJ1dGgtdXNlcnMiLCJpc3MiOiJjaGVydXRoLWFwaSJ9.PAm4NsaJKFlrCL3zcNjn-_e9iMfjy9HrT7n6RBVaD-c
Content-Type : application/json 

{
    "originalUrl": "https://www.youtube.com/watch?v=6zhGS79oQ4k&list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz&index=46",
    "title" : "Lower bound binary search"
}