POST http://localhost:3000/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzgxMzI1NjAxLCJleHAiOjE3ODEzMjkyMDEsImF1ZCI6ImNoZXJ1dGgtdXNlcnMiLCJpc3MiOiJjaGVydXRoLWFwaSJ9.O0muOs0F1JqnNn_hoBIWjm8xTETJqeELVAQQCGBaJxo
Content-Type : application/json 

{
    "originalUrl": "https://www.udemy.com/course/nestjs-masterclass-complete-course/learn/lecture/44530643#overview",
    "title":"Nestjs Course 3"
}