PATCH http://localhost:3000/api/urls/1
Content-Type: application/json

{
  "originalUrl": "https://googwle.com",
  "title": "Google",
  "expiresAt": "2007-01-16",
  "password": "password#123",
  "isActive": true
}
